service_names_to_ids = {
    "auth_broker": 1,
    "citb": 2,
    "content_delivery": 3,  # /PS-IGNORE
    "data_hub_crm": 4,
    "data_hub_mi": 5,
    "data_hub_omis": 6,  # /PS-IGNORE
    "data_protection": 7,
    "data_workspace": 8,
    "datahub": 9,
    "digital_workspace": 10,
    "directory": 11,
    "soo": 12,
    "eig": 13,
    "export_ops": 14,
    "export_vouchers": 15,
    "find_a_supplier": 16,
    "great": 17,
    "invest_in_gb": 20,
    "it_operations_support": 18,
    "it_ops_support": 19,
    "jupyterhub": 21,
    "l__letters": 22,
    "market_access": 23,
    "microsoft_teams": 24,
    "return_to_office": 25,
    "selling_online_overseas": 26,
    "single_sign_on": 27,
    "trade_remedy": 29,
    "uk_global_tariff": 30,
    "technology_service_solutions": 28,
    "check_export_duties": 31,
    "eu_exit": 32,
    "exceptional_review_process": 33,
    "twuk": 34,
    "export_support_service": 35,
    "ess_im_europe": 36,
    "im_eecan": 37,
    "im_south_asia": 38,
}
