# Generated by Django 4.1.2 on 2022-11-01 16:02

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HelpDeskCreds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("zendesk_email", models.EmailField(max_length=254)),
                ("zendesk_token", models.CharField(blank=True, max_length=255, null=True)),
                ("zendesk_subdomain", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "help_desk",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[("zendesk", "Zendesk"), ("halo", "Halo")],
                        default="zendesk",
                        max_length=7,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="helpdeskcreds",
            constraint=models.UniqueConstraint(
                fields=("zendesk_subdomain", "zendesk_email", "zendesk_token"),
                name="zendesk_subdomain_email_token",
            ),
        ),
    ]
