# Generated by Django 4.1.2 on 2022-11-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_desk_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpdeskcreds",
            name="halo_client_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="helpdeskcreds",
            name="halo_client_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
