# Generated by Django 4.1.2 on 2022-11-02 12:52

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("help_desk_api", "0002_helpdeskcreds_halo_client_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helpdeskcreds",
            name="help_desk",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("zendesk", "Zendesk"), ("halo", "Halo")], default="zendesk", max_length=12
            ),
        ),
    ]
