# Generated by Django 4.2.14 on 2024-07-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_desk_api", "0003_alter_helpdeskcreds_help_desk"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpdeskcreds",
            name="note",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
