# Generated by Django 4.2.14 on 2024-07-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_desk_api", "0004_helpdeskcreds_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Value",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("zendesk_value", models.CharField()),
                ("halo_id", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("zendesk_name", models.CharField(default="", verbose_name="Zendesk name")),
                ("halo_name", models.CharField(default="", verbose_name="Halo name")),
                ("zendesk_id", models.BigIntegerField(verbose_name="Zendesk ID")),
                ("halo_id", models.BigIntegerField(verbose_name="Halo ID")),
                (
                    "values",
                    models.ManyToManyField(
                        related_name="field",
                        to="help_desk_api.value",
                        verbose_name="Value mappings",
                    ),
                ),
            ],
        ),
    ]
