# Generated by Django 4.2.14 on 2024-08-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_desk_api", "0005_value_customfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfield",
            name="is_multiselect",
            field=models.BooleanField(default=False, verbose_name="Is multiselect?"),
        ),
    ]
