# Generated by Django 4.2.14 on 2024-08-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_desk_api", "0006_customfield_is_multiselect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="value",
            name="halo_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
