# Generated by Django 4.2.15 on 2024-08-27 14:08
from django.conf import settings
from django.core.management import call_command
from django.db import migrations


def load_custom_field_data(apps, schema_editor):
    data_path = settings.BASE_DIR / "help_desk_api/initial_data/custom_field_data.json"
    call_command("loaddata", data_path)


class Migration(migrations.Migration):

    dependencies = [
        ("help_desk_api", "0008_alter_customfield_values"),
    ]

    operations = [migrations.RunPython(load_custom_field_data, migrations.RunPython.noop)]
