FROM python:3.10-bullseye

ENV PYTHONUNBUFFERED=1  # /PS-IGNORE
ENV PYTHONDONTWRITEBYTECODE=1  # /PS-IGNORE
ENV POETRY_VIRTUALENVS_CREATE=false  # /PS-IGNORE

WORKDIR /app

RUN apt-get update -y

RUN pip install --upgrade pip
RUN pip install poetry

COPY poetry.lock pyproject.toml /app/

RUN poetry install --with dev,testing --without production

COPY . /app/
