user = {
    "user": {
        "id": 380271314777,
        "url": "https://uktrade.zendesk.com/api/v2/users/1.json",
        "name": "Example User",
        "email": "test@example.com",
        "created_at": "2021-03-19T10:46:43Z",
        "updated_at": "2023-06-08T08:58:47Z",
        "time_zone": "London",
        "iana_time_zone": "Europe/London",
        "phone": None,
        "shared_phone_number": None,
        "photo": None,
        "locale_id": 1176,
        "locale": "en-gb",
        "organization_id": None,
        "role": "admin",
        "verified": True,
        "authenticity_token": "9LtKORja3zUw3nCAidbUpnY2ttxQckanSZl2m/zf/H8=",
        "external_id": None,
        "tags": [],
        "alias": "",
        "active": True,
        "shared": False,
        "shared_agent": False,
        "last_login_at": "2023-06-08T08:58:43Z",
        "two_factor_auth_enabled": True,
        "signature": "",
        "details": "",
        "notes": "",
        "role_type": 4,
        "custom_role_id": 1900004401693,
        "moderator": True,
        "ticket_restriction": None,
        "only_private_comments": False,
        "restricted_agent": False,
        "suspended": False,
        "default_group_id": 26197325,
        "report_csv": False,
        "user_fields": {"city": None, "job_title": None},
    }
}
